## Imports

In [1]:
import numpy as np

In [2]:
import sys
sys.path.append('../')
from streetstudy.data import virat

## Load Data

In [3]:
video_df = virat.get_dataset_df()

In [4]:
video_path = "/mnt/d/data/virat/videos/VIRAT_S_000002.mp4"
events_df = virat.get_annotations_df(video_path, type='events')
objects_df = virat.get_annotations_df(video_path, type='object')
mapping_df = virat.get_annotations_df(video_path, type='mapping')

In [5]:
print(events_df.columns)
print(objects_df.columns)
print(mapping_df.columns)

Index(['event_id', 'event_type', 'duration', 'start_frame', 'end_frame',
       'current_frame', 'bbox_lefttop_x', 'bbox_lefttop_y', 'bbox_width',
       'bbox_height', 'bbox_rightbottom_x', 'bbox_rightbottom_y'],
      dtype='object')
Index(['object_id', 'object_duration', 'current_frame', 'bbox_lefttop_x',
       'bbox_lefttop_y', 'bbox_width', 'bbox_height', 'object_type'],
      dtype='object')
Index([      'event_id',     'event_type', 'event_duration',    'start_frame',
            'end_frame',        'num_obj',                6,                7,
                      8,                9,               10,               11,
                     12,               13,               14,               15,
                     16,               17,               18,               19,
                     20,               21,               22,               23,
                     24,               25,               26,               27],
      dtype='object')


## Preprocess Data

In [73]:
X = np.array([[1,3,5,61], [2,68,7,9]])
condition_1 = (X[:, 2]  == 5)
condition_2 = (X[:, 2]  < 10)
np.where([condition_1 & condition_2], [1], [0]).nonzero()

(array([0]), array([0]))

In [48]:
def get_object(obj_list, map_df, obj_id):
    selected_obj = obj_list[obj_list[:, 0] == obj_id]
    selected_obj = np.hstack((selected_obj, np.ones((selected_obj.shape[0], 1)) * -1))
    
    selected_events = mapping_df[mapping_df[object_id + 7] == 1]
    for _, event in selected_events.iterrows():
        condition_1 = selected_obj[:, 2] >= event['start_frame']
        condition_2 = selected_obj[:, 2] <= event['start_frame']
          
        selected_obj[(condition_1)&(condition_2)][:, -1]
        print(selected_obj)
#         selected_obj[:, -1] = np.select(condition_1 & condition_2, 1, default=0)
    
    return selected_obj

In [45]:
objects_list = objects_df.to_numpy()
print(objects_list.shape)
unique_objects = objects_df['object_id'].unique()
for object_id in unique_objects:
    print("ID:", object_id)
    X = get_object(objects_list, mapping_df, object_id)

(43532, 8)
ID: 2
ID: 3
ID: 4
[[ 4.000e+00  9.076e+03  0.000e+00 ...  1.070e+02  1.000e+00 -1.000e+00]
 [ 4.000e+00  9.076e+03  1.000e+00 ...  1.070e+02  1.000e+00 -1.000e+00]
 [ 4.000e+00  9.076e+03  2.000e+00 ...  1.070e+02  1.000e+00 -1.000e+00]
 ...
 [ 4.000e+00  9.076e+03  9.073e+03 ...  1.530e+02  1.000e+00 -1.000e+00]
 [ 4.000e+00  9.076e+03  9.074e+03 ...  1.530e+02  1.000e+00 -1.000e+00]
 [ 4.000e+00  9.076e+03  9.075e+03 ...  1.530e+02  1.000e+00 -1.000e+00]]
[[ 4.000e+00  9.076e+03  0.000e+00 ...  1.070e+02  1.000e+00 -1.000e+00]
 [ 4.000e+00  9.076e+03  1.000e+00 ...  1.070e+02  1.000e+00 -1.000e+00]
 [ 4.000e+00  9.076e+03  2.000e+00 ...  1.070e+02  1.000e+00 -1.000e+00]
 ...
 [ 4.000e+00  9.076e+03  9.073e+03 ...  1.530e+02  1.000e+00 -1.000e+00]
 [ 4.000e+00  9.076e+03  9.074e+03 ...  1.530e+02  1.000e+00 -1.000e+00]
 [ 4.000e+00  9.076e+03  9.075e+03 ...  1.530e+02  1.000e+00 -1.000e+00]]
[[ 4.000e+00  9.076e+03  0.000e+00 ...  1.070e+02  1.000e+00 -1.000e+00]
 [ 4.000e+

In [ ]:
dwelling_events = [1,2,3,4,5,6,7,8]

In [ ]:
dwelling_df = events_df[["current_frame", "bbox_lefttop_x", "bbox_lefttop_y", "bbox_rightbottom_x", "bbox_rightbottom_y", "event_type"]]

In [ ]:
for _, row in dwelling_df.iterrows():
    if row['event_type'] in dwelling_events:
        row['event_type'] = 1
    else:
        row['event_type'] = 0

In [ ]:
X = dwelling_df.drop(columns='event_type', inplace=False).to_numpy()
y = dwelling_df['event_type'].to_numpy()
print(X.shape, y.shape)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42, shuffle=False)
clf = LogisticRegression()
clf.fit(X_train, y_train)

In [ ]:
preds = clf.predict(X_test)
clf.score(X_test, y_test)